version: 2
jobs:
  build-clamav-image:
    docker:
      - image: circleci/ruby:2.6 # this doesn't matter, just using for consistency.
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          rev=$(git rev-parse --short HEAD)
          docker build -t logindotgov/secops-clamav:latest -t logindotgov/secops-clamav:"${rev}" .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push logindotgov/secops-clamav:"${rev}"
          docker push logindotgov/secops-clamav:latest
workflows:
  version: 2
  release:
    jobs:
      - build-clamav-image
